RESULT_SUCCESS = "success"
RESULT_FAILURE = "failure"
RESULT_CANCEL = "canceled"

HOST_RESULT_SUCCESS = RESULT_SUCCESS
HOST_RESULT_FAILURE = RESULT_FAILURE
HOST_RESULT_CANCEL = RESULT_CANCEL
HOST_RESULT_INFRA_FAILURE = "infrastructure-failure"

CANCEL_RESULT_CANCELLING = "cancelling"
CANCEL_RESULT_FAILURE = RESULT_FAILURE
CANCEL_RESULT_FINISHED = "finished"
